require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ExtendsController do

  # This should return the minimal set of attributes required to create a valid
  # Extend. As you add validations to Extend, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "body" => "MyText" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ExtendsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all extends as @extends" do
      extend = Extend.create! valid_attributes
      get :index, {}, valid_session
      assigns(:extends).should eq([extend])
    end
  end

  describe "GET show" do
    it "assigns the requested extend as @extend" do
      extend = Extend.create! valid_attributes
      get :show, {:id => extend.to_param}, valid_session
      assigns(:extend).should eq(extend)
    end
  end

  describe "GET new" do
    it "assigns a new extend as @extend" do
      get :new, {}, valid_session
      assigns(:extend).should be_a_new(Extend)
    end
  end

  describe "GET edit" do
    it "assigns the requested extend as @extend" do
      extend = Extend.create! valid_attributes
      get :edit, {:id => extend.to_param}, valid_session
      assigns(:extend).should eq(extend)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Extend" do
        expect {
          post :create, {:extend => valid_attributes}, valid_session
        }.to change(Extend, :count).by(1)
      end

      it "assigns a newly created extend as @extend" do
        post :create, {:extend => valid_attributes}, valid_session
        assigns(:extend).should be_a(Extend)
        assigns(:extend).should be_persisted
      end

      it "redirects to the created extend" do
        post :create, {:extend => valid_attributes}, valid_session
        response.should redirect_to(Extend.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved extend as @extend" do
        # Trigger the behavior that occurs when invalid params are submitted
        Extend.any_instance.stub(:save).and_return(false)
        post :create, {:extend => { "body" => "invalid value" }}, valid_session
        assigns(:extend).should be_a_new(Extend)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Extend.any_instance.stub(:save).and_return(false)
        post :create, {:extend => { "body" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested extend" do
        extend = Extend.create! valid_attributes
        # Assuming there are no other extends in the database, this
        # specifies that the Extend created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Extend.any_instance.should_receive(:update).with({ "body" => "MyText" })
        put :update, {:id => extend.to_param, :extend => { "body" => "MyText" }}, valid_session
      end

      it "assigns the requested extend as @extend" do
        extend = Extend.create! valid_attributes
        put :update, {:id => extend.to_param, :extend => valid_attributes}, valid_session
        assigns(:extend).should eq(extend)
      end

      it "redirects to the extend" do
        extend = Extend.create! valid_attributes
        put :update, {:id => extend.to_param, :extend => valid_attributes}, valid_session
        response.should redirect_to(extend)
      end
    end

    describe "with invalid params" do
      it "assigns the extend as @extend" do
        extend = Extend.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Extend.any_instance.stub(:save).and_return(false)
        put :update, {:id => extend.to_param, :extend => { "body" => "invalid value" }}, valid_session
        assigns(:extend).should eq(extend)
      end

      it "re-renders the 'edit' template" do
        extend = Extend.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Extend.any_instance.stub(:save).and_return(false)
        put :update, {:id => extend.to_param, :extend => { "body" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested extend" do
      extend = Extend.create! valid_attributes
      expect {
        delete :destroy, {:id => extend.to_param}, valid_session
      }.to change(Extend, :count).by(-1)
    end

    it "redirects to the extends list" do
      extend = Extend.create! valid_attributes
      delete :destroy, {:id => extend.to_param}, valid_session
      response.should redirect_to(extends_url)
    end
  end

end
